### ISSUE TITLE
Tokota Duplication

### ISSUE THREAD

**Issue by OceanFreezie** [EricaG13/Toko-HP-Journal-Gen#1] opened 2021-08-01 02:24 UTC
https://gyazo.com/fc6826c8964e631e0b182d61fcef0fa3 
https://gyazo.com/fa3873307fda92dc9f1496859b6530c2

Issue with pulling tokotas off the google sheet- tokotas are only listed once. I am using the fancy HP tracker. None of the names will load properly.

**Comment by kaycodes13** [comment] 2021-09-20 15:15
As of yesterday's update, tokota name duplication should be fixed. The patch is live on the website.

Some more technical details on the cause of the issue below, for the record:

This bug stemmed from an issue with how the code was searching and sorting tokotas. The sort algorithm was sorting case-insensitively but the search algorithm was searching case-sensitively, so the sort algorithm was putting some names in places the search algorithm didn't expect - in particular, whenever names were capitalized differently, such as REYNOLDS PAMPHLET there being in all-caps. This threw off the sorting of the entire list and made it impossible for the search algorithm to find many of tokotas.

If the search can't find a name in the list when it's reading the csv file, it assumes there is no tokota with that name yet and adds a new name to the list, which caused incorrectly sorted names to be duplicated several times. And if it can't find a name while generating a journal, it ends up trying to read from a section of the tokota list that doesn't exist, resulting in that "cannot read property of undefined" error.

Now that both the search and the sort operate case-sensitively, this issue should be gone.

**Closed as completed by kaycodes13** 2021-09-20 15:15 UTC
